#!/bin/sh -e

if [ "$#" -ne 1 ]; then
	echo "usage: $0 vitess_database_url";
	exit 1;
fi;

username="$(echo "${1}" | cut -d@ -f1 | cut -d/ -f3 | cut -d: -f1)";
password="$(echo "${1}" | cut -d@ -f1 | cut -d: -f3)";
host="$(echo "${1}" | cut -d@ -f2 | cut -d: -f1)";
port="$(echo "${1}" | cut -d@ -f2 | cut -d: -f2 | cut -d/ -f1)";
database="$(echo "${1}" | cut -d@ -f2 | cut -d/ -f2)";

(
	echo 'DROP TABLE IF EXISTS todos;';
	cat upstream/examples/mysql/todos/migrations/*.sql;
) | mysql --host "${host}" --port "${port}" --user "${username}" "-p${password}" "${database}" || exit 1;

docker build -t vitess/test/rust/sqlx .;
docker run --rm -i -e DATABASE_URL="${1}" vitess/test/rust/sqlx;

