#!/bin/sh -e

DATABASE_URL="mysql://${VT_USERNAME}:${VT_PASSWORD}@${VT_HOST}:${VT_PORT}/${VT_DATABASE}";

(
	echo 'DROP TABLE IF EXISTS todos;';
	cat upstream/examples/mysql/todos/migrations/*.sql;
) | mysql --host "${VT_HOST}" --port "${VT_PORT}" --user "${VT_USERNAME}" "-p${VT_PASSWORD}" "${VT_DATABASE}" || exit 1;

docker build --build-arg DATABASE_URL="${DATABASE_URL}" -t vitess/test/rust/sqlx .;
docker run --rm -i -e DATABASE_URL="${DATABASE_URL}" vitess/test/rust/sqlx;

