#!/bin/sh -e

if [ "$#" -ne 1 ]; then
	echo "usage: $0 vitess_database_url";
	exit 1;
fi;

docker build -t vitess/test/java/spring .

username="$(echo "${1}" | cut -d@ -f1 | cut -d/ -f3 | cut -d: -f1)";
password="$(echo "${1}" | cut -d@ -f1 | cut -d: -f3)";
host="$(echo "${1}" | cut -d@ -f2 | cut -d: -f1)";
port="$(echo "${1}" | cut -d@ -f2 | cut -d: -f2 | cut -d/ -f1)";
database="$(echo "${1}" | cut -d@ -f2 | cut -d/ -f2)";

docker run --rm -i -e DB_HOST="${host}" -e DB_PORT="${port}" -e DB_USERNAME="${username}" -e DB_PASSWORD="${password}" -e DB_NAME="${database}" vitess/test/java/spring

