#!/bin/sh

if [ "$#" -ne 1 ]; then
	echo "usage: $0 vitess_database_url";
	exit 1;
fi;

username="$(echo "${1}" | cut -d@ -f1 | cut -d/ -f3 | cut -d: -f1)";
password="$(echo "${1}" | cut -d@ -f1 | cut -d: -f3)";
host="$(echo "${1}" | cut -d@ -f2 | cut -d: -f1)";
port="$(echo "${1}" | cut -d@ -f2 | cut -d: -f2 | cut -d/ -f1)";
database="$(echo "${1}" | cut -d@ -f2 | cut -d/ -f2)";

docker run --rm -i "-v$(pwd)/src:/src.ro:ro" -e DB_HOST="${host}" -e DB_PORT="${port}" -e DB_USERNAME="${username}" -e DB_PASSWORD="${password}" -e DB_NAME="${database}" openjdk:alpine sh -ex -c 'cp -avf /src.ro /src; cd /src; apk add -U gettext jq curl; cat src/main/resources/application.properties.tpl | envsubst > src/main/resources/application.properties; ./gradlew --no-daemon test; timeout -t 30 ./gradlew --no-daemon bootRun & sleep 20; curl -v -X POST -d "name=username&email=useremail" localhost:8080/demo/add; curl -v localhost:8080/demo/all | jq; wait'

