#!/bin/bash

# General setup
git submodule update --init;

# TODO:  Start Vitess, and detect the database URL here
# TODO:  Run MySQL as well so we can compare results for both
if [ "$#" -ne 1 ]; then
	echo "usage: $0 vitess_database_url";
	exit 1;
fi;
VITESS_DATABASE_URL="$1";

for language in $(find . -mindepth 3 -maxdepth 3 -type f -name test | sed 's:^\./::' | xargs dirname | xargs dirname | sort -u); do
	echo "${language}:";
	for framework in $(find "${language}" -mindepth 2 -maxdepth 2 -type f -name test | sed 's:^\./::' | xargs dirname | xargs -n1 basename); do
		pushd "${language}/${framework}" >/dev/null;
		./test "${VITESS_DATABASE_URL}" &>/dev/null;
		echo "  ${framework}: $?";
		popd >/dev/null;
	done
done

