#!/bin/sh -e
cat src/main/resources/application.properties.tpl | envsubst > src/main/resources/application.properties;
./gradlew --no-daemon test;
timeout -t 30 ./gradlew --no-daemon bootRun &
sleep 20;
curl -v -X POST -d "name=username&email=useremail" localhost:8080/demo/add;
curl -v localhost:8080/demo/all | jq;

