#!/bin/bash -ex
dir="$(dirname "${0}")"
pip3 install pyyaml
export FILTER_FROM_STDIN=1
export OUTPUT=plain
"${dir}/get-changed-files" # print them here for debugging purposes
buildkite-agent meta-data set 'frameworks' "$(./tools/get-frameworks < <("${dir}/get-changed-files"))"

