version: '3.8'
services:
  db:
    image: mysql:5.7
    expose:
      - 3306
    restart: always
    environment:
      MYSQL_DATABASE: testing
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin ping"]
      start_period: 5s
      interval: 5s
      timeout: 2s
      retries: 5

