version: '3.8'
services:
  db:
    image: mysql:5.7
    ports:
      - 3306
    env:
      MYSQL_DATABASE: testing
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["mysqladmin", "ping"]
      interval: 5s
      timeout: 2s
      retries: 5

