#!/usr/bin/env python3

import subprocess
import sys

# template_mysql57 {{{
template_mysql57 = """
  - key: test-mysql57-%FRAMEWORK%
    label: "Test %FRAMEWORK% against MySQL 5.7"
    plugins:
      - docker-compose#v3.7.0:
        config:
          - docker-compose.mysql57.yml
          - docker-compose.yml
        run: test
        env:
          FRAMEWORK: "%FRAMEWORK%"
          VT_USERNAME: root
          VT_PASSWORD: root
          VT_DATABASE: testing
          VT_HOST: db
          VT_PORT: 3306
          VT_NUM_SHARDS: 1
          VT_DIALECT: mysql57
"""
# }}}
# template_mysql80 {{{
template_mysql80 = """
  - key: test-mysql80-%FRAMEWORK%
    label: "Test %FRAMEWORK% against MySQL 8.0"
    plugins:
      - docker-compose#v3.7.0:
        config:
          - docker-compose.mysql80.yml
          - docker-compose.yml
        run: test
        env:
          FRAMEWORK: "%FRAMEWORK%"
          VT_USERNAME: root
          VT_PASSWORD: root
          VT_DATABASE: testing
          VT_HOST: db
          VT_PORT: 3306
          VT_NUM_SHARDS: 1
          VT_DIALECT: mysql80
"""
# }}}
# template_vttestserver57 {{{
template_vttestserver57 = """
  - key: test-vttestserver57-%FRAMEWORK%
    label: "Test %FRAMEWORK% against vttestserver 5.7"
    depends_on: test-mysql57-%FRAMEWORK%
    plugins:
      - docker-compose#v3.7.0:
        config:
          - docker-compose.vttestserver57.yml
          - docker-compose.yml
        run: test
        env:
          FRAMEWORK: "%FRAMEWORK%"
          VT_USERNAME: root
          VT_PASSWORD: root
          VT_DATABASE: testing
          VT_HOST: db
          VT_PORT: 3306
          VT_NUM_SHARDS: 1
          VT_DIALECT: mysql57
"""
# }}}
# template_vttestserver80 {{{
template_vttestserver80 = """
  - key: test-vttestserver80-%FRAMEWORK%
    label: "Test %FRAMEWORK% against vttestserver 8.0"
    depends_on: test-mysql80-%FRAMEWORK%
    plugins:
      - docker-compose#v3.7.0:
        config:
          - docker-compose.vttestserver80.yml
          - docker-compose.yml
        run: test
        env:
          FRAMEWORK: "%FRAMEWORK%"
          VT_USERNAME: root
          VT_PASSWORD: root
          VT_DATABASE: testing
          VT_HOST: db
          VT_PORT: 3306
          VT_NUM_SHARDS: 1
          VT_DIALECT: mysql80
"""
# }}}
# template_vttestserver57sharded {{{
template_vttestserver57sharded = """
  - key: test-vttestserver57sharded-%FRAMEWORK%
    label: "Test %FRAMEWORK% against vttestserver 5.7 (sharded)"
    depends_on: test-vttestserver57-%FRAMEWORK%
    plugins:
      - docker-compose#v3.7.0:
        config:
          - docker-compose.vttestserver57sharded.yml
          - docker-compose.yml
        run: test
        env:
          FRAMEWORK: "%FRAMEWORK%"
          VT_USERNAME: root
          VT_PASSWORD: root
          VT_DATABASE: testing
          VT_HOST: db
          VT_PORT: 3306
          VT_NUM_SHARDS: 2
          VT_DIALECT: mysql57
"""
# }}}
# template_vttestserver80sharded {{{
template_vttestserver80sharded = """
  - key: test-vttestserver80sharded-%FRAMEWORK%
    label: "Test %FRAMEWORK% against vttestserver 8.0 (sharded)"
    depends_on: test-vttestserver80-%FRAMEWORK%
    plugins:
      - docker-compose#v3.7.0:
        config:
          - docker-compose.vttestserver80sharded.yml
          - docker-compose.yml
        run: test
        env:
          FRAMEWORK: "%FRAMEWORK%"
          VT_USERNAME: root
          VT_PASSWORD: root
          VT_DATABASE: testing
          VT_HOST: db
          VT_PORT: 3306
          VT_NUM_SHARDS: 2
          VT_DIALECT: mysql80
"""
 # }}}

agent = subprocess.Popen(['buildkite-agent', 'meta-data', 'get', 'changed-frameworks'], stdout = subprocess.PIPE) # TODO:  changed-frameworks vs frameworks based on env
result = ['  - wait']
for f in agent.stdout:
    f = f.decode('ascii').strip()
    result.append(template_mysql57.replace('%FRAMEWORK%', f))
    result.append(template_mysql80.replace('%FRAMEWORK%', f))
    result.append(template_vttestserver57.replace('%FRAMEWORK%', f))
    result.append(template_vttestserver80.replace('%FRAMEWORK%', f))
    result.append(template_vttestserver57sharded.replace('%FRAMEWORK%', f))
    result.append(template_vttestserver80sharded.replace('%FRAMEWORK%', f))
result = '\n'.join(result)

print(result)
agent = subprocess.run(['buildkite-agent', 'pipeline', 'upload'], input = result)

