#!/bin/bash

echo '--- get-changed-files env:'
env | sed 's/^/'$'\t''/'

if [ "${BUILDKITE_BRANCH}" == 'master' ]; then
	# This leans heavily on squashing when we push to master
	git diff --name-only HEAD~1..HEAD
else
	git fetch origin master
	git diff --name-only origin/master..HEAD
fi

