#!/bin/bash

if [ "${BUILDKITE_BRANCH}" == 'main' ]; then
	# This leans heavily on squashing when we push to main
	git diff --name-only HEAD~1..HEAD
else
	git fetch origin main
	git diff --name-only origin/main..HEAD
fi

