steps:
  - key: get-frameworks
    label: "Determine changed frameworks"
    command: ./.buildkite/get-changed-files && pip install pyyaml && buildkite-agent meta-data set "frameworks" "$(./tools/get-frameworks < <(./.buildkite/get-changed-files))"
    env:
      FILTER_FROM_STDIN: "1"
  - key: build
    label: "Build test containers"
    depends_on: get-frameworks
    command: buildkite-agent meta-data get "frameworks" | while read framework; do ./run.sh build_image "${framework}"; done

