steps:
  - key: get-frameworks
    label: "Determine changed frameworks"
    plugins:
      - docker#v3.8.0:
          image: python:3
          command: ["bash", "-c", "./.buildkite/get-changed-files && pip3 install pyyaml && buildkite-agent meta-data set \"frameworks\" \"$(./tools/get-frameworks < <(./.buildkite/get-changed-files))\""]
          mount-buildkite-agent: true
          environment:
            FILTER_FROM_STDIN: "1"
  - key: build
    label: "Build test containers"
    depends_on: get-frameworks
    command: buildkite-agent meta-data get "frameworks" | while read framework; do ./run.sh build_image "${framework}"; done

