steps:
  - key: get-frameworks
    label: "Determine changed frameworks"
    plugins:
      - docker#v3.8.0:
          image: python:3
          command: ["./.buildkite/determine-changed-frameworks"]
          mount-buildkite-agent: true
          mount-ssh-agent: true
  - key: build
    label: "Build test containers"
    depends_on: get-frameworks
    command: ./.buildkite/build-images

