#!/bin/sh

if [ "$#" -ne 1 ]; then
	echo "usage: $0 vitess_database_url";
	exit 1;
fi;

username="$(echo "${1}" | cut -d@ -f1 | cut -d/ -f3 | cut -d: -f1)";
password="$(echo "${1}" | cut -d@ -f1 | cut -d: -f3)";
host="$(echo "${1}" | cut -d@ -f2 | cut -d: -f1)";
port="$(echo "${1}" | cut -d@ -f2 | cut -d: -f2 | cut -d/ -f1)";
database="$(echo "${1}" | cut -d@ -f2 | cut -d/ -f2)";

echo 'DROP TABLE IF EXISTS products;' | mysql --host "${host}" --port "${port}" --user "${username}" "-p${password}" "${database}" &>/dev/null || exit 1;
docker run --rm -i "-v$(pwd):/src" -e DATABASE_URL="$1" golang bash -c 'cd /src; go run .' &>/dev/null;

