#!/bin/sh

if [ "$#" -ne 1 ]; then
	echo "usage: $0 vitess_database_url";
	exit 1;
fi;

docker build -t vitess/test/python/sqlalchemy .;
docker run --rm -i -e DATABASE_URL="${1}" vitess/test/python/sqlalchemy;

