#!/bin/sh

if [ "$#" -ne 1 ]; then
	echo "usage: $0 vitess_database_url";
	exit 1;
fi;

docker build -t vitess/test/ruby/rails .;

username="$(echo "${1}" | cut -d@ -f1 | cut -d/ -f3 | cut -d: -f1)";
password="$(echo "${1}" | cut -d@ -f1 | cut -d: -f3)";
host="$(echo "${1}" | cut -d@ -f2 | cut -d: -f1)";
port="$(echo "${1}" | cut -d@ -f2 | cut -d: -f2 | cut -d/ -f1)";
database="$(echo "${1}" | cut -d@ -f2 | cut -d/ -f2)";

(
	echo 'DROP TABLE IF EXISTS articles;';
	echo 'DROP TABLE IF EXISTS comments;';
) | mysql --host "${host}" --port "${port}" --user "${username}" "-p${password}" "${database}" || exit 1;
# TODO:  Test running, not just migrations:  bundle exec rails s -p 80 -b 0.0.0.0
# Note:  Have to do this janky thing where we copy /src because Rails likes to
#    write over db/schema.rb when it runs migrations
docker run --rm -i -e DATABASE_HOST="${host}" -e DATABASE_USERNAME="${username}" -e DATABASE_PASSWORD="${password}" -e DEVELOPMENT_DATABASE="${database}" -p8000:80 vitess/test/ruby/rails;

