#!/bin/sh -e

docker build -t vitess/test/javascript/sequelize .;

if [ "$#" -ne 1 ]; then
	echo "usage: $0 vitess_database_url";
	exit 1;
fi;

docker run --rm -i "-v$(pwd)/src:/src.ro:ro" -e DATABASE_URL="$1" vitess/test/javascript/sequelize;

