[package]
name = "mysql-test"
version = "0.1.0"
authors = ["Mike Cronce <mc@planetscale.com>"]
edition = "2018"

[dependencies]
mysql_async = "0.24"
tablefy = "0.1"
tablefy_derive = "0.2"
tokio = "0.2"
prettytable-rs = "0.8"

