#!/bin/sh

DATABASE_URL="mysql://${VT_USERNAME}:${VT_PASSWORD}@${VT_HOST}:${VT_PORT}/${VT_DATABASE}";
cd upstream/examples;
for file in $(find . -name '*.py'); do
	echo "file: ${file}";
	sed -i 's%create_engine("[^"]*"%create_engine("'"${DATABASE_URL}"'"%' "${file}";
	if [ "$(basename ${file})" != '__init__.py' ]; then 
		python3 "${file}";
		result="$?";
		if [ "$result" -ne 0 ]; then
			exit $result;
		fi;
	fi;
done;

