#!/bin/sh

if [ "$#" -ne 1 ]; then
	echo "usage: $0 vitess_database_url";
	exit 1;
fi;

# PyMySQL
echo '--- Running in `PyMySQL` framework';
pushd PyMySQL >/dev/null;
./test $@;
echo $?;
popd >/dev/null;

