#!/bin/sh -e

# TODO:  Test running, not just migrations:  apache2-foreground

env | grep -v " " > .env;
./artisan migrate:install --no-interaction
./artisan migrate:fresh --no-interaction
./artisan db:seed --no-interaction

