default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['VT_USERNAME'] %>
  password: <%= ENV['VT_PASSWORD'] %>
  host: <%= ENV['VT_HOST'] %>
  port: <%= ENV['VT_PORT'] %>
  variables:
    sql_mode: 'STRICT_ALL_TABLES,NO_AUTO_VALUE_ON_ZERO'

development:
  <<: *default
  database: <%= ENV['VT_DATABASE'] %>

production:
  <<: *default
  database: <%= ENV['PRODUCTION_DATABASE'] %>
  username: <%= ENV['PRODUCTION_DATABASE_USERNAME'] %>
  password: <%= ENV['PRODUCTION_DATABASE_PASSWORD'] %>
