#!/bin/sh -ex

cd upstream;
patch -p1 < ../__database.ts.patch;
cd src/packages/tests;

export TEST_MYSQL_BASE_URI="mysql://${VT_USERNAME}:${VT_PASSWORD}@${VT_HOST}:${VT_PORT}";
export TEST_MYSQL_URI="${TEST_MYSQL_BASE_URI}/${VT_DATABASE}";

env | grep 'VT_\|TEST_'

pnpm run jest integration/mysql -- --detectOpenHandles --maxConcurrency=1;

export TEST_MARIADB_BASE_URL="${TEST_MYSQL_BASE_URI}";
export TEST_MARIADB_URI="${TEST_MYSQL_URI}";
pnpm run jest integration/mariadb -- --detectOpenHandles --maxConcurrency=1;

