#!/usr/bin/env python3

import os
import sys
import yaml
import glob
import pathlib

def missing(list1, list2):
	return [v for v in list1 if v not in list2]

def frameworks_on_disk():
    frameworks = []
    for framework in glob.glob('frameworks/*/*'):
        framework_parts = pathlib.Path(framework).parts[1:]
        frameworks.append(str(pathlib.Path(*framework_parts)))

    return sorted(frameworks)

def frameworks_in_workflow(workflow_file):
    with open(os.path.join(".github", "workflows", workflow_file)) as workflow:
         config = yaml.load(workflow, Loader=yaml.SafeLoader)
         configured_frameworks = \
                config['jobs']['run_tests']['strategy']['matrix']['framework']

    return sorted(configured_frameworks)

def compare_for_workflow(workflow_file):
    on_disk = frameworks_on_disk()
    in_workflow = frameworks_in_workflow(workflow_file)

    missing_from_workflow = missing(on_disk, in_workflow)
    missing_from_disk = missing(in_workflow, on_disk)

    exit = True
    print("Workflow", workflow_file)
    if len(missing_from_workflow) > 0:
        exit = False
        print("  Missing from workflow:", missing_from_workflow)
    if len(missing_from_disk) > 0:
        exit = False
        print("  Missing from disk:", missing_from_disk)
    return exit

exit = 0
if(not compare_for_workflow("test.yml")):
    exit = 1
if(not compare_for_workflow("test-master.yml")):
    exit = 1

sys.exit(exit)

