#!/usr/bin/env python3

import yaml
import glob
import pathlib

def frameworks_on_disk():
    frameworks = []
    for framework in glob.glob('frameworks/*/*'):
        if not None:
            framework_parts = pathlib.Path(framework).parts[1:]
            frameworks.append(str(pathlib.Path(*framework_parts)))

    return sorted(frameworks)


def frameworks_in_workflow():
    with open(".github/workflows/test.yml") as workflow:
         config = yaml.load(workflow, Loader=yaml.SafeLoader)
         configured_frameworks = \
                config['jobs']['run_tests']['strategy']['matrix']['framework']

    return sorted(configured_frameworks)

on_disk = frameworks_on_disk()
in_workflow = frameworks_in_workflow()

assert on_disk == in_workflow, "There are missing frameworks in test.yml"
