#!/usr/bin/env python3

import json
import os
import sys
import yaml

frameworks = []
with open('.github/frameworks.yaml') as conf:
    config = yaml.load(conf, Loader=yaml.SafeLoader)
    frameworks = config['frameworks']

if(os.environ.get('FILTER_FROM_STDIN') != None):
    filter_frameworks = {}
    files = json.load(sys.stdin)
    print(json.dumps(files, indent = 4))
    for f in files:
        path = f.split(os.path.sep)
        if(len(path) < 3):
            continue
        if(path[0] != 'frameworks'):
            continue
        filter_frameworks[os.path.join(path[1], path[2])] = None
    frameworks = list(filter(lambda f: f in filter_frameworks, frameworks))

print('::set-output name=frameworks::' + json.dumps(frameworks))

