name: Linters
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run ShellCheck
        run: shellcheck *.sh


  framework_compare:
    name: Compare test.yml to workflows on disk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Compare on-disk to test.yml
        run: ./tools/compare-frameworks
