name: Linters
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  shellcheck:
    name: Check out the repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master

  
